### ISSUE TITLE
Complete list items

### ISSUE THREAD

**Issue by plfiorini** [hawaii-desktop/fluid#1]

**Comment by iBelieve** [comment]
@plfiorini I can work on this, bringing in the list items from QML Material and improving them/adding features as necessary. Do you have anything specific you want completed or added?

**Comment by plfiorini** [comment]
From the tech point of view I'd like to use the QQC2 ItemDelegate as a base.
Off the top of my head We need list items for titles (bold labels), icon + label, probably also icon + label with actions and icon + label + subtitle
